name: Rocker UAT
run-name: Rocker UAT
on: workflow_dispatch
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: shug0131/cctu
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Rocker script
        run: Rscript -e 'knitr::knit("validation.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -am 'Data updated' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
